name: Cypress Tests

on:
  push:
    branches:
      - first_tests
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Set environment variables
        run: |
          echo "CYPRESS_USER=${{ secrets.CYPRESS_USER }}" >> $GITHUB_ENV
          echo "CYPRESS_PASSWORD=${{ secrets.CYPRESS_PASSWORD }}" >> $GITHUB_ENV
          echo "CYPRESS_BASE_URL=${{ secrets.CYPRESS_BASE_URL }}" >> $GITHUB_ENV
          echo "CYPRESS_LANGUAGE=${{ secrets.CYPRESS_LANGUAGE }}" >> $GITHUB_ENV

      - name: Run Cypress tests
        run: npx cypress run --browser chrome