name: Cypress Tests

on:
  push:
    branches:
      - first_tests
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Set environment variables
        run: |
          echo "CYPRESS_USER=${{ secrets.CYPRESS_USER }}" >> $GITHUB_ENV
          echo "CYPRESS_PASSWORD=${{ secrets.CYPRESS_PASSWORD }}" >> $GITHUB_ENV
          echo "CYPRESS_BASE_URL=${{ secrets.CYPRESS_BASE_URL }}" >> $GITHUB_ENV
          echo "CYPRESS_LANGUAGE=${{ secrets.CYPRESS_LANGUAGE }}" >> $GITHUB_ENV

      - name: Install Xvfb and dependencies
        run: sudo apt-get install -y xvfb

      - name: Start Xvfb
        run: Xvfb :99 &

      - name: Run Cypress Login Tests
        run: DISPLAY=:99 npx cypress run --spec 'cypress/e2e/login.spec.ts' --browser chrome

      - name: Run Cypress Home Page Tests
        run: DISPLAY=:99 npx cypress run --spec 'cypress/e2e/homeTabs.spec.ts' --browser chrome

      - name: Run Cypress Header Tests
        run: DISPLAY=:99 npx cypress run --spec 'cypress/e2e/header.spec.ts' --browser chrome
